# Generated by Django 6.0.3 on 2026-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_service_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
