# Generated by Django 5.2.8 on 2026-03-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_team_name_alter_team_role'),
        ('products', '0002_alter_category_options_category_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='navbarcategory',
            options={'ordering': ['position'], 'verbose_name_plural': 'Navbar Categories'},
        ),
        migrations.RemoveField(
            model_name='navbarcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='navbarcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='navbarcategory',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_item', to='products.category'),
        ),
        migrations.AddField(
            model_name='navbarcategory',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
