# Generated by Django 5.2.8 on 2026-03-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_category_alter_navbarcategory_options_and_more'),
    ]

    operations = [
    ]
