# Generated by Django 5.2.8 on 2026-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
