# Generated by Django 6.0.3 on 2026-03-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
            preserve_default=False,
        ),
    ]
