# Generated by Django 5.2.8 on 2026-03-26 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_provider'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='providers.provider'),
        ),
    ]
